{application,euchre,
             [{description,"An OTP application"},
              {vsn,"0.1.0"},
              {registered,[]},
              {mod,{euchre_app,[]}},
              {applications,[kernel,stdlib]},
              {env,[]},
              {modules,[euchre_app,euchre_sup,game,game_server,player]},
              {maintainers,[]},
              {licenses,["Apache 2.0"]},
              {links,[]}]}.
